### ISSUE TITLE
Unable to load database names

### ISSUE THREAD

**Issue by fresheneesz** [paralect/robomongo#1011]
After upgrading to mongo 3.0, I'm getting the error:

```
Cannot connect to MongoDB (localhost:27017), error: Unable to load database names.
```

I can connect via the direct mongo shell from the console, but robo mongo can't connect. I've been able to connect before I upgraded. In fact, I was able to connect before I changed my config to YAML. My configuration is:

```
storage:
   dbPath: "/home/vagrant/backend/mongodata"
   engine: wiredTiger

systemLog:
   destination: file
   path: "/home/vagrant/backend/log/mongo.log"
   logAppend: true

net:
   bindIp: 127.0.0.1
   port: 27017
```

I'm using Robomongo 0.8.5
