### ISSUE TITLE
Please provide a PPA/DEB package

### ISSUE THREAD

**Issue by starfishmod** [paralect/robomongo#118]
It would be great if you could provide a PPA or deb package for Ubuntu

Thanks for a great bit of software :)

**Comment by hackel** [comment]
Yeah, this issue really needs to be reopened.  Providing binary-only packages that include separate libraries like the garbage Vagrant packages is insane.  It needs to be a priority to re-write this application so that it can use an unmodified mongoclient.  Specifying a specific required version in the package spec is no problem, but rolling your own just doesn't make sense.  Why wouldn't you be able to extend it to add whatever functionality you need?  Adding a librobomongo package would be a fine solution.  It's really sad to see so much catering to idiot OSX users.  Can't they just buy some proprietary solution, since they seem to love that crap so much?

**Comment by rbecheras** [comment]
@paralect ==> @schetnikovich @AlPatsino @anorsich @gavruk @myaskevich 

please reopen this issue... robomongo is great, a PPA could born .... nop ?

**Comment by simsekgokhan** [comment]
Hey guys, we have re-considered this and decided to work on producing DEB/PPA and also RPM packages. Added into our major wish list. Thanks a lot for your interest.

**Comment by rbecheras** [comment]
Thank you guys you rocks, it a great news ! Where would we found informations about the states of these goals ? Just in this issue for now ?

**Comment by simsekgokhan** [comment]
Yes, can be tracked in this issue or on twitter also: https://twitter.com/Robomongo

**Comment by rbecheras** [comment]
Thank you for your reactivity @simsekgokhan

**Comment by probonopd** [comment]
Maybe you could provide an [AppImage](http://appimage.org/) which would mean package once and run on all major desktop Linux distributions. [Many applications](https://github.com/probonopd/AppImageKit/wiki/AppImages) are already distributed this way.

**Comment by simsekgokhan** [comment]
Hi @probonopd , it seems like a very interesting idea/project which can make it very easy to support all linux distributions. We will investigate this solution more. Thanks a lot for the suggestion.

**Comment by rbecheras** [comment]
`AppImage` is great, event ideal to easy, quick and large scaled distribution, and to distribute the alpha/beta binary versions of our apps, no doubt.

But no doubt it's a complementary distribution system, yet. It can't and shouldn't replace any *nix specific package management system.

I'm not part of `Paralect` organization or `Robomongo` team, this is my own view but I'm pretty sure the large majority of *nix and open source soldiers share that point of view.

I think you (robomongo team) shouldn't do the choice to use `AppImage` without thinking about it as a complementary distribution system. Or you should explicitly explain that you provide an `AppImage`, and you charge each *nix community to do the job for its distro, staying in touch with them to support them officially.

Again, its my own thoughts, and I hope no body will feel any negative waves reading my words.

**Comment by probonopd** [comment]
AppImage is an additional distribution system specifically created to give upstream authors an easy channel to reach end users directly, without intermediaries in between, and without having to build different packages for each distribution and version. 

Of course traditional packages can continue to be built by distributions/packagers/maintainers.

**Comment by lafrech** [comment]
FWIW, here's the Request For Package for Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=812194. It was opened one year ago and shows no activity.

**Comment by chrisspen** [comment]
Where are current debs available? The current [download page](https://robomongo.org/download) only provides a tarball.

Old forum posts reference some deb download links like `https://download.robomongo.org/0.8.5/linux/robomongo-0.8.5-x86_64.deb` but these are ancient and don't work with the current version of Mongo. Moreover, replacing the URL's version number with 1.0.0 or an other more recent version returns a 404 error.

**Comment by tchwpkgorg** [comment]
+1

**Comment by dalvarezquiroga** [comment]
+1

**Comment by Demetrio92** [comment]
+1

**Comment by gufranco** [comment]
+1

**Comment by enp0s23** [comment]
+1

**Comment by basilky** [comment]
+1

**Comment by tolstenko** [comment]
+1

**Comment by D3473R** [comment]
One could use the [pkg2appimage](https://github.com/AppImage/pkg2appimage/blob/master/pkg2appimage) script with the following yml file:

```yml
 
app: Robo-3T

ingredients:
  script:
    - DLD=$(wget -q "https://api.github.com/repos/Studio3T/robomongo/releases/latest"  -O - | grep -E "https.*.tar.gz" | cut -d'"' -f4)
    - wget -c $DLD
    - echo $DLD | cut -d/ -f8 > VERSION
    - tar zxvf robo3t*tar.gz


script:
  - cp -r ../robo3t-*/* usr/
  - wget https://robomongo.org/static/robomongo-128x128-129df2f1.png -O robo3t.png
  - cat > robo3t.desktop <<EOF
  - [Desktop Entry]
  - Type=Application
  - Name=Robo-3T
  - Icon=robo3t
  - Exec=bin/robo3t %u
  - Categories=Development;Database;
  - Comment=Native cross-platform MongoDB management tool
  - EOF
```

Run it like this: `pkg2appimage robo3t.yml`.
